CREATE TABLE IF NOT EXISTS Updates (
	Id varchar(50) NOT NULL,
	Code varchar(50) NOT NULL,
	PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS Towns (
	Name varchar(50) NOT NULL,
	ExtraBlocks int NOT NULL DEFAULT 0,
	PRIMARY KEY (Name)
);

CREATE TABLE IF NOT EXISTS Residents (
	UUID varchar(255) NOT NULL,
	IsNPC boolean DEFAULT false,
	Joined int NOT NULL,
	LastLogin int NOT NULL,
	PRIMARY KEY (UUID)
);

CREATE TABLE IF NOT EXISTS Nations (
	Name varchar(50) NOT NULL,
	ExtraBlocks int NOT NULL DEFAULT 0,
	PRIMARY KEY(Name)
);

CREATE TABLE IF NOT EXISTS TownBlocks (
	Id int AUTO_INCREMENT,
	X int NOT NULL,
	Z int NOT NULL,
	Dim int NOT NULL,
	TownName varchar(50) NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY (TownName) REFERENCES Towns(Name) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS TownPlots (
	Id int AUTO_INCREMENT,
	X1 int NOT NULL,
	Y1 int NOT NULL,
	Z1 int NOT NULL,
	X2 int NOT NULL,
	Y2 int NOT NULL,
	Z2 int NOT NULL,
	Dim int NOT NULL,
	TownName varchar(50) NOT NULL,
	Owner varchar(255) DEFAULT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY (TownName) REFERENCES Towns(Name) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Owner) REFERENCES Residents(UUID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ResidentsToTowns (
	Id int AUTO_INCREMENT,
	TownName varchar(50) NOT NULL,
	Owner varchar(255) NOT NULL,
	Rank varchar(1) DEFAULT 'R',
	PRIMARY KEY (Id),
	FOREIGN KEY (TownName) REFERENCES Towns(Name) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Owner) REFERENCES Residents(UUID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TownsToNations (
	Id int AUTO_INCREMENT,
	TownName varchar(50) NOT NULL,
	NationName varchar(50) NOT NULL,
	Rank varchar(1) DEFAULT 'T',
	PRIMARY KEY (Id),
	FOREIGN KEY (TownName) REFERENCES Towns(Name) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (NationName) REFERENCES Nations(Name) ON DELETE CASCADE ON UPDATE CASCADE
);